project:
  type: website

website:
  title: "sam | science"
  site-url: "https://samalbers.science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/boshek
      - icon: twitter
        href: https://twitter.com/big_bad_sam
      - icon: rss-fill
        href: index.xml
        aria-label: RSS
  twitter-card: true
  open-graph: true
format:
  html:
    self-contained: true
    link-external-newwindow: true
    theme:
      light: [flatly, urchin.scss]
      dark: [darkly, urchin-black.scss]
    css: styles.css
    toc: true
execute: 
  freeze: true



