project:
  type: website

website:
  title: "sam | science"
  site-url: https://samalbers.science
  repo-url: https://github.com/boshek/samalbers.science
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: urchin.scss
    css: styles.css



